export const questions = [
  {
    number: 1,
    state: "andhra-pradesh",
    question: "What is the capital of Andhra Pradesh?",
    answer: "Amaravati",
  },
  {
    number: 2,
    state: "arunachal-pradesh",
    question: "What is the capital of Arunachal Pradesh?",
    answer: "Itanagar",
  },
  {
    number: 3,
    state: "assam",
    question: "What is the capital of Assam?",
    answer: "Dispur",
  },
  {
    number: 4,
    state: "bihar",
    question: "What is the capital of Bihar?",
    answer: "Patna",
  },
  {
    number: 5,
    state: "chhattisgarh",
    question: "What is the capital of Chhattisgarh?",
    answer: "Raipur",
  },
  {
    number: 6,
    state: "goa",
    question: "What is the capital of Goa?",
    answer: "Panaji",
  },
  {
    number: 7,
    state: "gujarat",
    question: "What is the capital of Gujarat?",
    answer: "Gandhinagar",
  },
  {
    number: 8,
    state: "haryana",
    question: "What is the capital of Haryana?",
    answer: "Chandigarh",
  },
  {
    number: 9,
    state: "himachal-pradesh",
    question: "What is the capital of Himachal Pradesh?",
    answer: "Shimla",
  },
  {
    number: 10,
    state: "jharkhand",
    question: "What is the capital of Jharkhand?",
    answer: "Ranchi",
  },
  {
    number: 11,
    state: "karnataka",
    question: "What is the capital of Karnataka?",
    answer: "Bengaluru",
  },
  {
    number: 12,
    state: "kerala",
    question: "What is the capital of Kerala?",
    answer: "Thiruvananthapuram",
  },
  {
    number: 13,
    state: "madhya-pradesh",
    question: "What is the capital of Madhya Pradesh?",
    answer: "Bhopal",
  },
  {
    number: 14,
    state: "maharashtra",
    question: "What is the capital of Maharashtra?",
    answer: "Mumbai",
  },
  {
    number: 15,
    state: "manipur",
    question: "What is the capital of Manipur?",
    answer: "Imphal",
  },
  {
    number: 16,
    state: "meghalaya",
    question: "What is the capital of Meghalaya?",
    answer: "Shillong",
  },
  {
    number: 17,
    state: "mizoram",
    question: "What is the capital of Mizoram?",
    answer: "Aizawl",
  },
  {
    number: 18,
    state: "nagaland",
    question: "What is the capital of Nagaland?",
    answer: "Kohima",
  },
  {
    number: 19,
    state: "odisha",
    question: "What is the capital of Odisha?",
    answer: "Bhubaneswar",
  },
  {
    number: 20,
    state: "punjab",
    question: "What is the capital of Punjab?",
    answer: "Chandigarh",
  },
  {
    number: 21,
    state: "rajasthan",
    question: "What is the capital of Rajasthan?",
    answer: "Jaipur",
  },
  {
    number: 22,
    state: "sikkim",
    question: "What is the capital of Sikkim?",
    answer: "Gangtok",
  },
  {
    number: 23,
    state: "tamil-nadu",
    question: "What is the capital of Tamil Nadu?",
    answer: "Chennai",
  },
  {
    number: 24,
    state: "telangana",
    question: "What is the capital of Telangana?",
    answer: "Hyderabad",
  },
  {
    number: 25,
    state: "tripura",
    question: "What is the capital of Tripura?",
    answer: "Agartala",
  },
  {
    number: 26,
    state: "uttar-pradesh",
    question: "What is the capital of Uttar Pradesh?",
    answer: "Lucknow",
  },
  {
    number: 27,
    state: "uttarakhand",
    question: "What is the capital of Uttarakhand?",
    answer: "Dehradun",
  },
  {
    number: 28,
    state: "west-bengal",
    question: "What is the capital of West Bengal?",
    answer: "Kolkata",
  },
];
